In [1]:
import numpy as np
import sys
from pathlib import Path
PROJECT_ROOT = Path("../").resolve()
sys.path.append(str(PROJECT_ROOT))

from src.features.sbert_features import SBERTFeatureExtractor
from src.utils.utils import load_csv
from src.config import (
    CLEANED_TRAIN_PATH,
    CLEANED_TEST_PATH,
    TRAIN_LABEL_PATH,
    FINAL_TRAIN_SBERT_PURE_PATH,
    FINAL_TEST_SBERT_PURE_PATH
)


# Load data
train_df = load_csv(CLEANED_TRAIN_PATH)
test_df = load_csv(CLEANED_TEST_PATH)
y_train = load_csv(TRAIN_LABEL_PATH)

# Convert label (nếu cần)
y_train_pure = (y_train - 1).values.ravel()

# ===== SBERT ONLY =====
sbert = SBERTFeatureExtractor()

print("🚀 Encoding TRAIN with SBERT only...")
X_train_pure = sbert.transform(train_df)

print("🚀 Encoding TEST with SBERT only...")
X_test_pure = sbert.transform(test_df)

# Save dataset
np.save(FINAL_TRAIN_SBERT_PURE_PATH, X_train_pure)
np.save(FINAL_TEST_SBERT_PURE_PATH, X_test_pure)

print("✔ Saved SBERT-only dataset!")
print("Train shape:", X_train_pure.shape)
print("Test shape:", X_test_pure.shape)

/Users/nhatnam/Documents/DM_252/Assignment/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Loaded SPECTER2 model: allenai/specter2_base on cpu
🚀 Encoding TRAIN with SBERT only...
🚀 Encoding TEST with SBERT only...
✔ Saved SBERT-only dataset!
Train shape: (510, 768)
Test shape: (86, 768)


In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from src.config import SUBMISSION_PURE_SBERT_PATH


# 3. Logistic Regression cơ bản nhất
baseline_model = LogisticRegression(class_weight='balanced', max_iter=2000)

# 4. Kiểm tra CV
cv_scores = cross_val_score(baseline_model, X_train_pure, y_train_pure, cv=5, scoring='f1_macro')
print(f"✔ PURE SBERT CV Macro F1-Score: {cv_scores.mean():.4f}")

# 5. Predict & Submit
baseline_model.fit(X_train_pure, y_train_pure)
y_pred_baseline = baseline_model.predict(X_test_pure) + 1

submission_base = pd.DataFrame({
    "id": test_df["id"],
    "Label": y_pred_baseline
})
submission_base.to_csv(SUBMISSION_PURE_SBERT_PATH, index=False)
print("✔ Saved PURE baseline submission")

✔ PURE SBERT CV Macro F1-Score: 0.3001
✔ Saved PURE baseline submission


In [3]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

print(f"\n====================")
print(f"MODEL: SBERT + OPTIMIZED PCA + SVM")
print(f"====================")

# 1. Pipeline hoàn chỉnh: Chuẩn hóa -> Giảm chiều -> Phân loại
pipe = Pipeline([
    ('scaler', StandardScaler()), # Chuẩn hóa giúp PCA tìm thành phần chính chuẩn xác hơn
    ('pca', PCA(random_state=42)),
    ('clf', SVC(class_weight='balanced', random_state=42))
])

# 2. Định nghĩa Lưới tham số (Grid) để máy tính tự dò tìm
param_grid = {
    'pca__n_components': [30, 50, 80, 120, 200], # Quét mọi mức cắt giảm chiều
    'clf__kernel': ['linear', 'rbf'],            # Thử cả ranh giới tuyến tính và phi tuyến
    'clf__C': [0.5, 1.0, 5.0, 10.0]              # Mức độ phạt khi mô hình phân loại sai
}

# 3. Khởi tạo và chạy Grid Search (Quét 5 x 2 x 4 = 40 kịch bản)
print("✔ Đang tự động dò tìm cấu trúc PCA tốt nhất (vui lòng đợi vài giây)...")
grid = GridSearchCV(pipe, param_grid, cv=5, scoring='f1_macro', n_jobs=-1, verbose=1)
grid.fit(X_train_pure, y_train_pure)

print(f"\n✔ Best CV Macro F1-Score: {grid.best_score_:.4f}")
print(f"✔ Best Params Found: {grid.best_params_}")

# 4. Lưu lại submission từ mô hình tốt nhất vừa tìm được
best_model = grid.best_estimator_
y_pred_best = best_model.predict(X_test_pure) + 1 # Nhớ cộng 1

submission_best_pca = pd.DataFrame({
    "id": test_df["id"],
    "Label": y_pred_best
})
submission_best_pca.to_csv("submission_sbert_best_pca.csv", index=False)
print("✔ Saved Optimized SBERT + PCA submission")


MODEL: SBERT + OPTIMIZED PCA + SVM
✔ Đang tự động dò tìm cấu trúc PCA tốt nhất (vui lòng đợi vài giây)...
Fitting 5 folds for each of 40 candidates, totalling 200 fits

✔ Best CV Macro F1-Score: 0.3221
✔ Best Params Found: {'clf__C': 1.0, 'clf__kernel': 'linear', 'pca__n_components': 30}
✔ Saved Optimized SBERT + PCA submission


In [3]:
# ============================================
# Evaluate LLM ASP-Relevance Scoring using Ollama
# ============================================

import pandas as pd
import ollama
import json

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score
)

from tqdm import tqdm

import sys
from pathlib import Path

PROJECT_ROOT = Path("../").resolve()
sys.path.append(str(PROJECT_ROOT))

from src.config import CLEANED_TRAIN_PATH

# ======================
# Load train data
# ======================

train_df = pd.read_csv(CLEANED_TRAIN_PATH)

print(train_df.columns)

# ======================
# Better SYSTEM PROMPT
# ======================

SYSTEM_PROMPT = """
You are an expert in Answer Set Programming (ASP),
logic programming,
knowledge representation,
nonmonotonic reasoning,
SAT solving,
and constraint solving.

Your task is to rate how relevant a research paper is
to ASP researchers.

Scoring rubric:

1 = Completely unrelated to ASP or logic programming
Examples:
- Computer vision
- CNN image classification
- Generic NLP
- Networking
- Databases
- Bioinformatics

2 = Slightly related to AI/reasoning but not ASP-focused
Examples:
- General machine learning
- Data mining
- Generic optimization
- Reinforcement learning

3 = Relevant to ASP researchers but not central ASP
Examples:
- SAT solving
- SMT solving
- Constraint programming
- Planning
- Automated reasoning

4 = Strongly relevant to ASP
Examples:
- Logic programming
- Stable model semantics
- ASP grounding
- Nonmonotonic reasoning
- ASP systems

5 = Core ASP contribution
Examples:
- New ASP semantics
- ASP solver advances
- ASP optimization techniques
- Foundational ASP theory
- ASP competitions
- ASP benchmarks

Example 1:
Title: Deep Residual Networks for Image Recognition
Score: 1

Example 2:
Title: Constraint Satisfaction Techniques in AI Planning
Score: 3

Example 3:
Title: Advances in Stable Model Semantics for ASP
Score: 5

Important:
- SAT/SMT/CSP papers are usually 3 unless tightly connected to ASP.
- Logic programming papers are usually 4-5.
- Machine learning papers are usually 1-2.

Respond ONLY with valid JSON.

Format:
{"score": <1-5>, "reason": "<short reason>"}
"""

# ======================
# Query Ollama
# ======================

def score_paper(title, abstract):

    prompt = f"""
Title: {title}

Abstract: {abstract}
"""

    try:

        response = ollama.chat(
            model="qwen2.5:7b",
            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            options={
                "temperature": 0
            }
        )

        text = response["message"]["content"].strip()

        # Debug raw output
        print("\nRAW RESPONSE:")
        print(text)

        # Remove markdown fences if model adds them
        text = text.replace("```json", "")
        text = text.replace("```", "")
        text = text.strip()

        result = json.loads(text)

        score = int(result["score"])

        # Clamp score to 1-5
        score = max(1, min(5, score))

        return {
            "score": score,
            "reason": result["reason"]
        }

    except Exception as e:

        print("ERROR:", e)

        return {
            "score": None,
            "reason": str(e)
        }

# ======================
# Run on train set
# ======================

N_SAMPLES = 50

subset_df = train_df.head(N_SAMPLES).copy()

llm_scores = []
llm_reasons = []

for _, row in tqdm(subset_df.iterrows(), total=len(subset_df)):

    title = str(row["title"])
    abstract = str(row["abstract"])

    result = score_paper(title, abstract)

    llm_scores.append(result["score"])
    llm_reasons.append(result["reason"])

# ======================
# Save predictions
# ======================

subset_df["llm_score"] = llm_scores
subset_df["llm_reason"] = llm_reasons

# ======================
# Evaluate MULTICLASS
# ======================

valid_df = subset_df[
    subset_df["llm_score"].notna()
]

y_true = valid_df["Label"].astype(int)
y_pred = valid_df["llm_score"].astype(int)

print("\n====================")
print("LLM Evaluation")
print("====================")

print("Accuracy:", accuracy_score(y_true, y_pred))

print("\nClassification Report:")
print(
    classification_report(
        y_true,
        y_pred,
        digits=3
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_true, y_pred))

# ======================
# Wrong predictions
# ======================

wrong_df = valid_df[
    valid_df["Label"] != valid_df["llm_score"]
]

print("\n====================")
print("Wrong Predictions")
print("====================")

display(
    wrong_df[
        [
            "title",
            "Label",
            "llm_score",
            "llm_reason"
        ]
    ].head(20)
)

# ======================
# Save
# ======================

subset_df.to_csv(
    "train_llm_scored.csv",
    index=False
)

print("\nSaved to train_llm_scored.csv")

Index(['title', 'venue', 'year', 'authors', 'doi', 'Label', 'id', 'abstract'], dtype='object')


  2%|▏         | 1/50 [00:03<02:35,  3.18s/it]


RAW RESPONSE:
{"score": 3, "reason": "Relevant to ASP researchers as it deals with rule languages and reasoning over streams, but not central to ASP."}


  4%|▍         | 2/50 [00:05<02:01,  2.52s/it]


RAW RESPONSE:
{"score": 4, "reason": "Relevant to ASP researchers as it uses Answer Set Programming and focuses on legal reasoning, but not a core ASP contribution."}


  6%|▌         | 3/50 [00:06<01:37,  2.07s/it]


RAW RESPONSE:
{"score": 3, "reason": "Focuses on argumentation theory and frameworks, which is relevant but not central to ASP."}


  8%|▊         | 4/50 [00:08<01:25,  1.86s/it]


RAW RESPONSE:
{"score": 3, "reason": "Relevant to AI/active reasoning but not central to ASP"}


 10%|█         | 5/50 [00:09<01:19,  1.77s/it]


RAW RESPONSE:
{"score": 3, "reason": "Relevant to planning but not central to ASP"}


 12%|█▏        | 6/50 [00:12<01:33,  2.12s/it]


RAW RESPONSE:
{"score": 3, "reason": "While the paper introduces an extension of perceptron operators, it is focused on description logics rather than ASP. It may be relevant for researchers interested in knowledge representation and logic programming, but not specifically for ASP."}


 14%|█▍        | 7/50 [00:13<01:14,  1.74s/it]


RAW RESPONSE:
{"score": 1, "reason": "Not related to ASP or logic programming."}


 16%|█▌        | 8/50 [00:14<01:04,  1.55s/it]


RAW RESPONSE:
{"score": 3, "reason": "Relevant to AI planning but not central to ASP"}


 18%|█▊        | 9/50 [00:17<01:19,  1.93s/it]


RAW RESPONSE:
{"score": 3, "reason": "Relevant to ASP researchers as it deals with planning and action domain model acquisition, which are related to nonmonotonic reasoning and logic programming, but not specifically focused on ASP."}


 20%|██        | 10/50 [00:18<01:07,  1.69s/it]


RAW RESPONSE:
{"score": 4, "reason": "Introduces a new syntax and semantics for ASP, relevant to core ASP theory"}


 22%|██▏       | 11/50 [00:20<01:09,  1.78s/it]


RAW RESPONSE:
{"score": 4, "reason": "Relevant to ASP researchers as it applies ASP to a real-world problem and discusses planning tasks, which is central to ASP."}


 24%|██▍       | 12/50 [00:22<01:09,  1.84s/it]


RAW RESPONSE:
{"score": 3, "reason": "Relevant to ASP researchers as it deals with epistemic reasoning and public announcement logic, which are related to nonmonotonic reasoning and knowledge representation."}


 26%|██▌       | 13/50 [00:23<01:02,  1.68s/it]


RAW RESPONSE:
{"score": 3, "reason": "While related to logic programming, it focuses on dynamic logic rather than ASP."}


 28%|██▊       | 14/50 [00:25<00:53,  1.48s/it]


RAW RESPONSE:
{"score": 1, "reason": "Unrelated to ASP or logic programming"}


 30%|███       | 15/50 [00:26<00:55,  1.58s/it]


RAW RESPONSE:
{"score": 4, "reason": "Relevant to ASP researchers as it uses ASP for solving a planning problem related to action reversibility."}


 32%|███▏      | 16/50 [00:28<00:55,  1.62s/it]


RAW RESPONSE:
{"score": 3, "reason": "Relevant to ASP researchers as it involves Answer Set Programming for generating planning tasks, but not central to ASP itself."}


 34%|███▍      | 17/50 [00:29<00:50,  1.54s/it]


RAW RESPONSE:
{"score": 3, "reason": "Relevant to ASP researchers as Prolog is a logic programming language, but not central to ASP-specific topics."}


 36%|███▌      | 18/50 [00:32<00:58,  1.83s/it]


RAW RESPONSE:
{"score": 3, "reason": "Relevant to ASP researchers as it deals with logic-based formalisms (Datalog) and explainability in graph neural networks, which are related to knowledge representation and reasoning."}


 38%|███▊      | 19/50 [00:34<01:03,  2.05s/it]


RAW RESPONSE:
{"score": 3, "reason": "While the paper discusses graph neural networks (GNNS) and their relation to Datalog, it is more focused on machine learning techniques rather than core ASP concepts."}


 40%|████      | 20/50 [00:37<01:02,  2.07s/it]


RAW RESPONSE:
{"score": 4, "reason": "Relevant to ASP researchers as it deals with stable model semantics and non-monotonic reasoning, which are central concepts in ASP."}


 42%|████▏     | 21/50 [00:37<00:49,  1.72s/it]


RAW RESPONSE:
{"score": 3, "reason": "Related to probabilistic reasoning but not specifically ASP"}


 44%|████▍     | 22/50 [00:39<00:48,  1.72s/it]


RAW RESPONSE:
{"score": 4, "reason": "Focuses on extending ASP with quantification and presents an algorithm related to policy extraction, which is relevant to ASP researchers."}


 46%|████▌     | 23/50 [00:42<00:53,  1.96s/it]


RAW RESPONSE:
{"score": 3, "reason": "The paper deals with data cleaning and entity resolution, which are relevant to ASP researchers but not specifically focused on ASP. It uses logical rules and constraints, which are related to logic programming."}


 48%|████▊     | 24/50 [00:44<00:49,  1.92s/it]


RAW RESPONSE:
{"score": 4, "reason": "Focuses on reasoning about answer sets and facets, which are central concepts in ASP."}


 50%|█████     | 25/50 [00:45<00:47,  1.89s/it]


RAW RESPONSE:
{"score": 2, "reason": "While related to AI and reasoning, it focuses on reinforcement learning and safety shields, which are not central to ASP."}


 52%|█████▏    | 26/50 [00:48<00:48,  2.04s/it]


RAW RESPONSE:
{"score": 3, "reason": "Relevant to ASP researchers as it deals with temporal logics and reactive synthesis, which are related to nonmonotonic reasoning and logic programming concepts."}


 54%|█████▍    | 27/50 [00:49<00:43,  1.87s/it]


RAW RESPONSE:
{"score": 2, "reason": "While it involves AI, it focuses on machine learning and autonomous vehicles rather than ASP."}


 56%|█████▌    | 28/50 [00:50<00:35,  1.61s/it]


RAW RESPONSE:
{"score": 4, "reason": "Discusses nonmonotonic reasoning which is relevant to ASP"}


 58%|█████▊    | 29/50 [00:51<00:28,  1.35s/it]


RAW RESPONSE:
{"score": 1, "reason": "Computer vision and image processing"}


 60%|██████    | 30/50 [00:52<00:26,  1.31s/it]


RAW RESPONSE:
{"score": 4, "reason": "Relates to nonmonotonic reasoning and default theories, which are relevant to ASP."}


 62%|██████▏   | 31/50 [00:53<00:23,  1.23s/it]


RAW RESPONSE:
{"score": 4, "reason": "Focuses on ASP semantics and possibly new theoretical contributions to the field"}


 64%|██████▍   | 32/50 [00:55<00:27,  1.53s/it]


RAW RESPONSE:
{"score": 3, "reason": "Relevant to ASP researchers as it discusses advancements in Prolog, a form of logic programming, but not specifically focused on ASP."}


 66%|██████▌   | 33/50 [00:57<00:27,  1.59s/it]


RAW RESPONSE:
{"score": 4, "reason": "Focuses on ASP tools and extensions, relevant to ASP researchers"}


 68%|██████▊   | 34/50 [00:59<00:24,  1.52s/it]


RAW RESPONSE:
{"score": 4, "reason": "Focuses on ASP applications in product configuration, which is relevant to ASP researchers."}


 70%|███████   | 35/50 [01:01<00:28,  1.90s/it]


RAW RESPONSE:
{"score": 4, "reason": "Relevant to ASP researchers as it deals with non-monotonic reasoning, which is central to ASP. The use of default logic for handling contradictions aligns well with ASP's stable model semantics."}


 72%|███████▏  | 36/50 [01:04<00:27,  1.97s/it]


RAW RESPONSE:
{"score": 4, "reason": "Focuses on ASP extensions and solver advances for algebraic answer set counting"}


 74%|███████▍  | 37/50 [01:05<00:25,  1.97s/it]


RAW RESPONSE:
{"score": 4, "reason": "Relevant to ASP researchers as it discusses non-monotonic reasoning and fixpoint theory, which are central concepts in ASP."}


 76%|███████▌  | 38/50 [01:08<00:24,  2.02s/it]


RAW RESPONSE:
{"score": 3, "reason": "While the paper focuses on structured argumentation and dialogue, which are related to nonmonotonic reasoning, it does not directly address ASP or its core components."}


 78%|███████▊  | 39/50 [01:09<00:21,  1.96s/it]


RAW RESPONSE:
{"score": 1, "reason": "The abstract does not mention ASP or any related concepts and is focused on digital oratory and linguistics."}


 80%|████████  | 40/50 [01:11<00:19,  1.92s/it]


RAW RESPONSE:
{"score": 4, "reason": "Relevant to ASP researchers, focusing on probabilistic extensions and complexity analysis of ASP."}


 82%|████████▏ | 41/50 [01:13<00:17,  1.93s/it]


RAW RESPONSE:
{"score": 5, "reason": "Core ASP contribution related to semantics and fixpoints"}


 84%|████████▍ | 42/50 [01:16<00:16,  2.05s/it]


RAW RESPONSE:
{"score": 3, "reason": "While the paper focuses on natural language generation, it uses Answer Set Programming for grammatical framework construction and demonstrates potential relevance to ASP through its application."}


 86%|████████▌ | 43/50 [01:18<00:14,  2.05s/it]


RAW RESPONSE:
{"score": 4, "reason": "Relevant to ASP researchers, focusing on treewidth and grounding processes in answer set programming."}


 88%|████████▊ | 44/50 [01:19<00:11,  1.91s/it]


RAW RESPONSE:
{"score": 3, "reason": "Contains multiple papers on knowledge representation and reasoning, some may be relevant to ASP researchers but not centrally focused on ASP."}


 90%|█████████ | 45/50 [01:22<00:10,  2.17s/it]


RAW RESPONSE:
{"score": 3, "reason": "The paper focuses on knowledge representation and reasoning using natural language, which is relevant to ASP researchers. However, it does not specifically address ASP or its core techniques."}


 92%|█████████▏| 46/50 [01:23<00:07,  1.93s/it]


RAW RESPONSE:
{"score": 1, "reason": "Completely unrelated to ASP or logic programming"}


 94%|█████████▍| 47/50 [01:25<00:05,  1.89s/it]


RAW RESPONSE:
{"score": 4, "reason": "Relevant to ASP researchers as it involves knowledge representation and uses semantic technologies, which are closely related to ASP."}


 96%|█████████▌| 48/50 [01:27<00:03,  1.76s/it]


RAW RESPONSE:
{"score": 3, "reason": "While it involves logic programming, it focuses more on the implementation in Isabelle rather than ASP."}


 98%|█████████▊| 49/50 [01:27<00:01,  1.49s/it]


RAW RESPONSE:
{"score": 1, "reason": "Completely unrelated to ASP or logic programming"}


100%|██████████| 50/50 [01:29<00:00,  1.80s/it]


RAW RESPONSE:
{"score": 3, "reason": "Relevant to ASP researchers as it involves planning and timed automata, but not specifically focused on ASP."}

LLM Evaluation
Accuracy: 0.2

Classification Report:
              precision    recall  f1-score   support

           1      0.333     0.143     0.200        14
           2      0.500     0.167     0.250         6
           3      0.174     0.500     0.258         8
           4      0.167     0.273     0.207        11
           5      0.000     0.000     0.000        11

    accuracy                          0.200        50
   macro avg      0.235     0.216     0.183        50
weighted avg      0.218     0.200     0.173        50


Confusion Matrix:
[[2 1 8 2 1]
 [2 1 1 2 0]
 [0 0 4 4 0]
 [1 0 7 3 0]
 [1 0 3 7 0]]

Wrong Predictions


,title,Label,llm_score,llm_reason
0,tabled clp for reasoning over stream data,1,3,Relevant to ASP researchers as it deals with r...
1,xai-law: a logic programming tool for modeling...,5,4,Relevant to ASP researchers as it uses Answer ...
2,workshop proceedings of the 40th international...,1,3,Focuses on argumentation theory and frameworks...
3,probabilistic active goal recognition,5,3,Relevant to AI/active reasoning but not centra...
4,heuristic strategies for accelerating multi-ag...,1,3,Relevant to planning but not central to ASP
6,action languages and covid-19: lessons learned,2,1,Not related to ASP or logic programming.
7,flexible lifelong explainable and robust solut...,4,3,Relevant to AI planning but not central to ASP
8,planning domain model acquisition from state t...,1,3,Relevant to ASP researchers as it deals with p...
9,chrvis: syntax and semantics,1,4,"Introduces a new syntax and semantics for ASP,..."
10,exploring neurosymbolic systems in answer set ...,5,4,Relevant to ASP researchers as it applies ASP ...



Saved to train_llm_scored.csv
